import type { SpellTemplate, UnitKind, UnitTemplate } from "./types";

// ============================================================================
// 兵种数据
// 设计：步兵→克骑兵 / 骑兵→克弓箭手 / 弓箭手→克步兵
// ============================================================================

export const UNIT_TEMPLATES: Record<UnitKind, UnitTemplate> = {
  infantry: {
    kind: "infantry",
    name: "步兵",
    emoji: "⚔️",
    hp: 60,
    attack: 12,
    defense: 8,
    speed: 4,
    moveRange: 2,
    attackRange: 1,
    counters: { cavalry: 1.5 },
    desc: "长枪克骑兵，攻防兼备",
  },
  shieldman: {
    kind: "shieldman",
    name: "盾兵",
    emoji: "🛡️",
    hp: 90,
    attack: 8,
    defense: 14,
    speed: 3,
    moveRange: 2,
    attackRange: 1,
    counters: { cavalry: 1.5 },
    desc: "血厚防高，肉盾首选，攻击力低",
  },
  archer: {
    kind: "archer",
    name: "弓箭手",
    emoji: "🏹",
    hp: 35,
    attack: 14,
    defense: 4,
    speed: 6,
    moveRange: 3,
    attackRange: 4,
    counters: { infantry: 1.5 },
    desc: "远程克步兵，近战脆",
  },
  cavalry: {
    kind: "cavalry",
    name: "骑兵",
    emoji: "🐎",
    hp: 50,
    attack: 16,
    defense: 6,
    speed: 9,
    moveRange: 4,
    attackRange: 1,
    counters: { archer: 1.5, elf_archer: 1.5 },
    desc: "高速冲锋，克弓箭手，惧长枪",
  },
  priest: {
    kind: "priest",
    name: "祭司",
    emoji: "🧙",
    hp: 30,
    attack: 6,
    defense: 4,
    speed: 6,
    moveRange: 3,
    attackRange: 3,
    counters: {},
    desc: "远程治疗：攻击友军 = 恢复 HP；攻击力低",
  },
  // ── Chapter 2 敌方专用 ──
  elf_archer: {
    kind: "elf_archer",
    name: "精灵弓",
    emoji: "🧝",
    hp: 28,
    attack: 16,
    defense: 3,
    speed: 7,
    moveRange: 3,
    attackRange: 5,
    counters: { infantry: 1.5, shieldman: 1.5 },
    desc: "强力远程，射程更远，但极脆",
  },
  treant: {
    kind: "treant",
    name: "树人",
    emoji: "🌳",
    hp: 200,
    attack: 18,
    defense: 12,
    speed: 2,
    moveRange: 1,
    attackRange: 1,
    counters: { archer: 1.5, elf_archer: 1.5 },
    desc: "巨大缓慢，超高血防，皮糙肉厚怼远程",
  },
  spider: {
    kind: "spider",
    name: "蜘蛛",
    emoji: "🕷️",
    hp: 25,
    attack: 10,
    defense: 2,
    speed: 7,
    moveRange: 3,
    attackRange: 1,
    counters: { archer: 1.5, elf_archer: 1.5 },
    desc: "速度快血量低，群战压垮射手",
  },
  // ── Chapter 3 敌方专用 ──
  skeleton: {
    kind: "skeleton",
    name: "骷髅兵",
    emoji: "💀",
    hp: 30,
    attack: 10,
    defense: 4,
    speed: 5,
    moveRange: 2,
    attackRange: 1,
    counters: {},
    desc: "数量多的亡灵杂兵",
  },
  zombie: {
    kind: "zombie",
    name: "僵尸",
    emoji: "🧟",
    hp: 80,
    attack: 14,
    defense: 8,
    speed: 2,
    moveRange: 2,
    attackRange: 1,
    counters: {},
    desc: "缓慢但耐打的腐尸",
  },
  skeleton_archer: {
    kind: "skeleton_archer",
    name: "骷髅弓",
    emoji: "🏴‍☠️",
    hp: 25,
    attack: 14,
    defense: 2,
    speed: 6,
    moveRange: 3,
    attackRange: 5,
    counters: { infantry: 1.3, shieldman: 1.3 },
    desc: "亡灵远程射手",
  },
  necromancer: {
    kind: "necromancer",
    name: "死灵法师",
    emoji: "🧙‍♂️",
    hp: 60,
    attack: 12,
    defense: 4,
    speed: 5,
    moveRange: 3,
    attackRange: 4,
    counters: {},
    desc: "亡灵之主，远程施法者",
  },
};

export function unitTemplate(kind: UnitKind): UnitTemplate {
  return UNIT_TEMPLATES[kind];
}

// ============================================================================
// 法术数据（v0.1 凯瑟琳的 3 个）
// ============================================================================

export const SPELL_TEMPLATES: Record<string, SpellTemplate> = {
  heal: {
    id: "heal",
    name: "治疗",
    emoji: "✨",
    manaCost: 4,
    target: "ally_unit",
    range: "single",
    desc: "为目标友军恢复 HP",
    baseValue: 30,
  },
  haste: {
    id: "haste",
    name: "加速",
    emoji: "💨",
    manaCost: 3,
    target: "ally_unit",
    range: "single",
    desc: "目标本回合移动距离 +2",
    baseValue: 2,
  },
  judgment: {
    id: "judgment",
    name: "神圣审判",
    emoji: "⚡",
    manaCost: 6,
    target: "enemy_unit",
    range: "single",
    desc: "对单个敌人造成神圣伤害（无视护甲）",
    baseValue: 35,
  },
  thorn_arrow: {
    id: "thorn_arrow",
    name: "荆棘箭",
    emoji: "🌿",
    manaCost: 4,
    target: "enemy_unit",
    range: "single",
    desc: "对敌人造成自然伤害（部分无视护甲）",
    baseValue: 30,
  },
  rally: {
    id: "rally",
    name: "集结号",
    emoji: "🎺",
    manaCost: 5,
    target: "self_party",
    range: "single",
    desc: "全体友军 +3 攻击，持续 1 回合",
    baseValue: 3,
  },
};
